spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seguradora?createDatabaseIfNotExist=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate # Hibernate não cria nem altera tabelas
